# BEGIN Cabinet
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} /+[^\.]+$
RewriteRule ^cabinet/forgot-password/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/forgot-password/index.php [L,QSA]
RewriteRule ^cabinet/forgot-password/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/cabinet/forgot-password/index.php [L,QSA]
RewriteRule ^ups/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/ups/$1 [L,QSA]
RewriteRule ^ups/((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/ups/$1  [L,QSA]
RewriteRule ^cabinet/assets/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/cabinet/assets/$1 [L,QSA]
RewriteRule ^cabinet/img/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/img/$1 [L,QSA]
RewriteRule ^cabinet/files/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/files/$1 [L,QSA]
RewriteRule ^cabinet/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=main [L,QSA]
RewriteRule ^cabinet/action/((.*)+)$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=load&method=json&a2=$1 [L,QSA]
RewriteRule ^cabinet/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=main [L,QSA]
RewriteRule ^cabinet/forgot-password/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/cabinet/forgot-password/index.php [L,QSA]
RewriteRule ^cabinet/profile.get?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=profile [L,QSA]
RewriteRule ^cabinet/profile.do?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=profile&a2=save [L,QSA]
RewriteRule ^cabinet/pm/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=pm [L,QSA]
RewriteRule ^cabinet/pm/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=pm [L,QSA]
RewriteRule ^cabinet/earn/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=friends [L,QSA]
RewriteRule ^cabinet/earn/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=friends [L,QSA]
RewriteRule ^cabinet/faq/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=faq [L,QSA]
RewriteRule ^cabinet/faq/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=faq [L,QSA]
RewriteRule ^cabinet/examples/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=examples [L,QSA]
RewriteRule ^cabinet/examples/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=examples [L,QSA]
RewriteRule ^cabinet/discount/?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=discount [L,QSA]
RewriteRule ^cabinet/discount/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=discount [L,QSA]
RewriteRule ^cabinet/open/((.*[^/])+)[/.*]?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=open_zakaz&id=$1 [L,QSA]
RewriteRule ^cabinet/read/((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=open_zakaz&id=$1 [L,QSA]
RewriteRule ^cabinet/add-file/((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=open_zakaz&id=$1&a2=file_add [L,QSA]
RewriteRule ^cabinet/premoder/zakaz-((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=open_pre&id=$1 [L,QSA]
RewriteRule ^cabinet/edit/zakaz-((.*)+).do?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=edit_zakaz&id=$1&a2=edit&a3=do [L,QSA]
RewriteRule ^cabinet/edit/zakaz-((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=edit_zakaz&id=$1&a2=edit [L,QSA]
RewriteRule ^cabinet/comment.do?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=zakaz_comm [L,QSA]
RewriteRule ^cabinet/pm.do?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/cabinet/pm_send.php [L,QSA]
RewriteRule ^cabinet/action.do?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=modal.do [L,QSA]
RewriteRule ^cabinet/action.get?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=modal [L,QSA]
RewriteRule ^cabinet/zakaz.write?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=open_new [L,QSA]
RewriteRule ^cabinet/zakaz.add?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/index.php?a=zakaz_add_do [L,QSA]
RewriteRule ^cabinet/cabinet/zakaz.update?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/zakaz_update_do.php [L,QSA]
Redirect 301 /exit/ /exit
RewriteRule ^exit/((.*)+)?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/do_logout.php [L,QSA]
RewriteRule ^exit?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/do_logout.php [L,QSA]
RewriteRule ^exit/index.php?$ /<?= NA5KU_PLUGIN_DIR_URL_WITHOUT_DOMAIN ?>cabinet/do_logout.php [L,QSA]
# END Cabinet
